import logo from '../assets/logo.png';
import adaga from '../assets/adaga.png';
import axe from '../assets/axe.svg';
import chariot from '../assets/chariot.svg';
import compass from '../assets/compass.svg';
import shield from '../assets/escudo.png';
import fast from '../assets/fast.svg';
import helmet from '../assets/helmet.svg';
import instagram from '../assets/instagram.svg';
import axePhoto from '../assets/machado.png';
import runes from '../assets/runes.svg';
import ship from '../assets/ship.svg';
import sword from '../assets/sword.svg';
import trash from '../assets/trash.svg';
import upload from '../assets/upload.svg';
import whatsapp from '../assets/whatsapp.svg';
import banner from '../assets/Banner.png';
import swordAlt from '../assets/sword_alt.png';
import lineDecoration from '../assets/linedecoration.svg';
import lineDecorationBlue from '../assets/linedecorationblue.svg';

export const Logo = logo;
export const Adaga = adaga;
export const Axe = axe;
export const Chariot = chariot;
export const Compass = compass;
export const Shield = shield;
export const Fast = fast;
export const Helmet = helmet;
export const Instagram = instagram;
export const AxePhoto = axePhoto;
export const Runes = runes;
export const Ship = ship;
export const Sword = sword;
export const Trash = trash;
export const Upload = upload;
export const Whatsapp = whatsapp;
export const BannerImage = banner;
export const SwordAlt = swordAlt;
export const LineDecoration = lineDecoration;
export const LineDecorationBlue = lineDecorationBlue;

